on: 
    push
    
name: Azure ARM
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@main

              # Log into Azure
            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZ_CREDS }}

              # Deploy Bicep file
            - name: deploy
              uses: azure/arm-deploy@v1
              with:
                  subscriptionId: ${{ variables.AZURE_SUBSCRIPTION }}
                  resourceGroupName: ${{ variables.AZURE_RG }}
                  template: ./infra/main.bicep
                  parameters: storagePrefix=stg
                  failOnStdErr: false
